baseURL: https://robertowebsite.netlify.app/
languageCode: en-us
title: Forty
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      My mom always said life was like a box of chocolates. You never know what you're gonna get.
    title: Hi, my name is Roberto and welcome to my platform!
  blog: {}
  contact:
    address:
      - city: London, ST NW1 6UK
        country: United Kingdom
        street: Regent's Park 191
        title:  London Business School
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: rkeaney.mfa2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: (123) 1234-4657 x1234
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Ooooops
    text: I did it again...
  favicon: favicon.ico
  footer:
    copyright: Roberto Keaney
    enable: yes
    quicklinks:
      - alt: Click here to find this genious
        text: 'RK Style: '
        url: https://www.linkedin.com/in/robertojohnkeaney/
    social:
      #- icon: fa-twitter
      #  label: Twitter
    #    url: https://www.twitter.com
      #- icon: fa-facebook
       # label: Facebook
     #   url: https://www.facebook.com
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/robertojkeaney/
      - icon: fa-github
        label: GitHub
        url: https://github.com/RKeaney/WebsiteAssignmentRK
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/robertojohnkeaney/
  image: ''
  name: Roberto Keaney
  navigation:
    #button1:
    #  - name: Get Started
      #  url: blogs
    #button2:
     # - name: Log In
      #  url: '#'
    links:
      - name: Home
        url: '#'
      - name: My CV
        url: blogs/CV
      - name: LBS Experience
        url: blogs/aliquam
      - name: Coding
        url: blogs/magna
    menu: Menu
    subtitle: By Roberto Keaney
    title: HOME
  tiles:
    enable: yes
    showcase:
      - image: LBS.jpg
        subtitle: Work hard play hard
        title: LBS Experience
        url: blogs/aliquam
      - image: pic02.jpg
        subtitle: My most recently updated
        title: My CV
        url: blogs/CV
      - image: pic0101.jpg
        subtitle: Coding Group Assignment
        title: Coding
        url: blogs/magna
      #- image: pic04.jpg
       # subtitle: Nisl Sed Aliquam
       # title: Ipsum
       # url: blogs/ipsum
      #- image: pic05.jpg
       # subtitle: Ipsum Dolor Sit Amet
      #  title: Consequat
       # url: blogs/ipsum
      #- image: pic06.jpg
       # subtitle: Feugiat Amet Tempus
        #title: Etiam
        #url: blogs/Roberto
  #two:
   # buttonText: Next
    #enable: yes
    #subtitle: "I hope you are enjoying my website, if you would like to see more detailed information, I recommend you to select one of the pages."
    #title: Lets get going!
    #url: blogs
